version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webfinal
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      retries: 20

  db_loader:
    image: postgres:16
    container_name: db_loader
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_dump.dump:/db_dump.dump
    entrypoint: ["sh", "-c", "until pg_isready -h postgres -U postgres; do sleep 2; done && psql -h postgres -U postgres -d webfinal < db_dump.dump"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webfinal
      PGPASSWORD: password

  app:
    build:
      context: ./WebFinal
      dockerfile: Dockerfile
    container_name: my_app
    ports:
        - "8080:8080"
    depends_on:
      db_loader:
        condition: service_completed_successfully
    environment:
      ConnectionStrings__Default: "Host=postgres;Username=postgres;Password=password;Database=webfinal"

volumes:
  pgdata: